# ClusterIssuer for Let's Encrypt Production
# This resource configures cert-manager to use Let's Encrypt for certificate issuance
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email address for Let's Encrypt account notifications
    # IMPORTANT: Set LETSENCRYPT_EMAIL environment variable before applying
    email: ${LETSENCRYPT_EMAIL}
    
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    
    # Solvers for ACME challenges
    solvers:
    # HTTP-01 challenge solver
    - http01:
        ingress:
          class: openshift-default
    
    # DNS-01 challenge solver (commented out - configure based on your DNS provider)
    # - dns01:
    #     cloudflare:
    #       email: your-email@example.com
    #       apiTokenSecretRef:
    #         name: cloudflare-api-token
    #         key: api-token

---
# ClusterIssuer for Let's Encrypt Staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email address for Let's Encrypt account notifications
    # IMPORTANT: Set LETSENCRYPT_EMAIL environment variable before applying
    email: ${LETSENCRYPT_EMAIL}
    
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    
    # Solvers for ACME challenges
    solvers:
    - http01:
        ingress:
          class: openshift-default

# Made with Bob
